config/routes.rb
Rails.application.routes.draw do
  resources :perfomances
  resources :reviews
  resources :sessions
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/perfomance.rb
class Perfomance < ApplicationRecord
  has_many :sessions, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :title, presence: true
  validates :duration, presence: true
  validates :age_rating, presence: true
  validates :release_date, presence: true

  validate :validate_duration_format
  validate :validate_age_rating_format

  private

  def validate_duration_format
    if duration.present? && duration <= 0
      errors.add(:duration, "должно быть больше 0")
    end
  end

  def validate_age_rating_format
    if age_rating.present? && age_rating !~ /\A\d{1,2}\+\z/
      errors.add(:age_rating, "должно быть в формате '12+''")
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :perfomance

  validates :user_name, presence: true
  validates :rating, presence: true
  validates :review_text, presence: true
  validates :review_date, presence: true

  validate :validate_rating_range
  validate :validate_review_date_format

  private

  def validate_rating_range
    if rating.present? && !(1..10).include?(rating)
      errors.add(:rating, "должен быть в диапазоне от 1 до 10")
    end
  end

  def validate_review_date_format
    if review_date.present? && review_date > Date.today
      errors.add(:review_date, "не может быть в будущем")
    end
  end

end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :perfomance

  validates :perfomance, presence: true
  validates :hall_number, presence: true
  validates :start_date, presence: true
  validates :start_time, presence: true

  validate :validate_hall_number
  validate :validate_start_date_in_future

  private

  def validate_hall_number
    if hall_number.present? && hall_number <= 0
      errors.add(:hall_number, "должен быть больше 0")
    end
  end

  def validate_start_date_in_future
    if start_date.present? && start_date < Date.today
      errors.add(:start_date, "не может быть в прошлом")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/perfomances_controller.rb
class PerfomancesController < ApplicationController
  before_action :set_perfomance, only: [ :show, :edit, :update, :destroy ]

  def index
    @perfomances = Perfomance.all
  end

  def new
    @perfomance = Perfomance.new
  end

  def show
    @sessions = @perfomance.sessions
    @reviews = @perfomance.reviews
  end

  def create
    @perfomance = Perfomance.new(perfomance_params)

    if @perfomance.save
      redirect_to perfomances_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @perfomance.update(perfomance_params)
      redirect_to @perfomance
    else
      render :edit
    end
  end

  def destroy
    @perfomance.destroy
    redirect_to perfomances_path
  end

  private

  def set_perfomance
    @perfomance = Perfomance.find(params[:id])
  end

  def perfomance_params
    params.require(:perfomance).permit(:title, :duration, :age_rating, :release_date)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  def index
    @reviews = Review.all
  end

  def show
    @other_reviews = Review.where(user_name: @review.user_name).where.not(id: @review.id)
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)

    if @review.save
      redirect_to reviews_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to @review
    else
      render :edit
    end
  end

  def destroy
    @review.destroy
    redirect_to reviews_path
  end

  private

  def set_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:perfomance_id, :user_name, :rating, :review_text, :review_date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :set_session, only: [:show, :edit, :update, :destroy]

  def index
    @sessions = Session.all
  end

  def show
  end

  def new
    @session = Session.new
  end

  def create
    @session = Session.new(session_params)

    if @session.save
      redirect_to sessions_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @session.update(session_params)
      redirect_to @session
    else
      render :edit
    end
  end

  def destroy
    @session.destroy
    redirect_to sessions_path
  end

  private

  def set_session
    @session = Session.find(params[:id])
  end

  def session_params
    params.require(:session).permit(:perfomance_id, :hall_number, :start_date, :start_time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/perfomances_helper.rb
module PerfomancesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.erb
<body>
  <h1 class="title">Добро пожаловать в театр им. А.С. Агаджанян</h1>

  <div class="tabs">
    <ul>
      <li><%= link_to 'Спектакли', perfomances_path %></li>
      <li><%= link_to 'Сеансы', sessions_path %></li> 
      <li><%= link_to 'Отзывы', reviews_path %></li>
    </ul>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Theatre" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/perfomances/_perfomance_form.html.erb
<%= form_with(model: @perfomance, local: true) do |form| %>
  <% if @perfomance.errors.any? %>
    <div>
      <h2>Ошибки:</h2>
      <ul>
        <% @perfomance.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="center_perfomance">
    <div>
      <div class='text'>
        <%= form.label :title, "Название:" %>
        <%= form.text_field :title %>
      </div>

      <div class='text'>
        <%= form.label :duration, "Продолжительность (мин):" %>
        <%= form.number_field :duration, min: 1 %>
      </div>

      <div class='text'>
        <%= form.label :age_rating, "Возрастное ограничение:" %>
        <%= form.text_field :age_rating, pattern: '\\d{1,2}\\+' %>
      </div>

      <div class='text'>
        <%= form.label :release_date, "Дата выпуска:" %>
        <%= form.date_select :release_date, start_year: 1900, end_year: Time.now.year %>
      </div>
    </div>
  </div>

  <div class="but">
    <ul>
      <div>
        <%= link_to 'Назад', @perfomance.new_record? ? perfomances_path : perfomance_path(@perfomance), class: 'button' %>
        <%= form.submit @perfomance.new_record? ? 'Добавить спектакль' : 'Сохранить изменения', class: 'button' %>
    </div>
    </ul>
  </div>
<% end %>

app/views/perfomances/edit.html.erb
<h1>Изменить спектакль</h1>
<%= render 'perfomance_form' %>

app/views/perfomances/index.html.erb
<h1>Список спектаклей</h1>

<hr>
<div class='main'>
  <% @perfomances.each do |perfomance| %>
    <div>
      <%= link_to "#{perfomance.title} (#{perfomance.release_date.strftime('%Y')})", perfomance_path(perfomance), class: "perfomance-link" %>
      <div>
        <span>Продолжительность: <%= perfomance.duration %> мин</span>
      </div>
    </div>
    <hr>
  <% end %>
</div>

<div class="but">
  <ul>
    <%= link_to "Назад", root_path, class: "button" %>
    <%= link_to "Добавить новый спектакль", new_perfomance_path, class: "button" %>
  </ul>
</div>

app/views/perfomances/new.html.erb
<h1>Добавить новый спектакль</h1>
<%= render 'perfomance_form' %>

app/views/perfomances/show.html.erb
<h1>Спектакль: <%= @perfomance.title %></h1>

<div>
  <p><strong>Дата выхода:</strong> <%= @perfomance.release_date.strftime('%d.%m.%Y') %></p>
  <p><strong>Продолжительность:</strong> <%= @perfomance.duration %> мин.</p>
  <p><strong>Возрастное ограничение:</strong> <%= @perfomance.age_rating %></p>
</div>

<div class="actions">
  <%= link_to "Назад", perfomances_path, class: "button" %>
  <%= link_to "Изменить", edit_perfomance_path(@perfomance), class: "button" %>
  <%= form_with model: @perfomance, method: :delete do |form| %>
    <button type="submit" onclick="return confirm('Удалить этот спектакль?')" class="button">
      Удалить
    </button>
  <% end %>
</div>

<div>
  <h2>Сеансы</h2>
  <% if @sessions.any? %>
    <div>
      <h3>Будущие сеансы:</h3>
      <% future_sessions = @sessions.select { |session| session.start_date >= DateTime.now } %>
      <% if future_sessions.any? %>
        <% future_sessions.each do |session| %>
          <strong>Зал:</strong> <%= session.hall_number %> |
          <strong>Дата:</strong> <%= session.start_date.strftime('%d.%m.%Y') %> |
          <strong>Время:</strong> <%= session.start_time.strftime('%H:%M') %>
          <hr>
        <% end %>
      <% else %>
        <p>Будущих сеансов для этого спектакля пока нет.</p>
      <% end %>
    </div>

    <div>
      <h3>Завершённые сеансы:</h3>
      <% past_sessions = @sessions.select { |session| session.start_date < DateTime.now } %>
      <% if past_sessions.any? %>
        <% past_sessions.each do |session| %>
          <strong>Зал:</strong> <%= session.hall_number %> |
          <strong>Дата:</strong> <%= session.start_date.strftime('%d.%m.%Y') %> |
          <strong>Время:</strong> <%= session.start_time.strftime('%H:%M') %>
          <hr>
        <% end %>
      <% else %>
        <p>Завершённых сеансов для этого спектакля пока нет.</p>
      <% end %>
    </div>

  <% else %>
    <p>Сеансов для этого спектакля пока нет.</p>
  <% end %>
</div>

<div>
  <h2>Отзывы</h2>
  <% if @reviews.any? %>
    <% @reviews.each do |review| %>
      <div class="review">
        <p><strong>Автор:</strong> <%= review.user_name %></p>
        <p><strong>Оценка:</strong> <%= review.rating %> / 10</p>
        <p><strong>Отзыв:</strong> <%= review.review_text %></p>
        <p><strong>Дата отзыва:</strong> <%= review.review_date.strftime('%d.%m.%Y') %></p>
        <hr>
      </div>
    <% end %>
  <% else %>
    <p>Отзывов для этого спектакля пока нет.</p>
  <% end %>
</div>

app/views/reviews/_review_form.html.erb
<%= form_with(model: @review, local: true) do |form| %>
  <% if @review.errors.any? %>
    <div>
      <h2>Ошибки:</h2>
      <ul>
        <% @review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="center">
    <div>
      <div class="text">
        <%= form.label :perfomance_id, "Выберите спектакль" %>
        <%= form.collection_select :perfomance_id, Perfomance.all, :id, :title %>
      </div>

      <div class="text">
        <%= form.label :user_name, "Автор отзыва" %>
        <%= form.text_field :user_name %>
      </div>

      <div class="text">
        <%= form.label :rating, "Оценка" %>
        <%= form.number_field :rating, min: 1, max: 10 %>
      </div>

      <div class="text">
        <%= form.label :review_date, "Дата отзыва" %>
        <%= form.date_field :review_date %>
      </div>

      <div class="text">
        <%= form.label :review_text, "Отзыв" %>
        <%= form.text_area :review_text, rows: 4 %>
      </div>
    </div>
  </div>

  <div class="but">
    <ul>
      <%= link_to 'Назад', @review.new_record? ? reviews_path : review_path(@review), class: 'button' %>
      <%= form.submit @review.new_record? ? 'Добавить отзыв' : "Сохранить изменения", class: 'button' %>
    </ul>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Изменить отзыв</h1>
<%= render 'review_form' %>

app/views/reviews/index.html.erb
<h1>Список отзывов</h1>

<hr>
<div class='main'>
  <% @reviews.each do |review| %>
    <div>
      <%= link_to "#{review.user_name}", review_path(review), class: "perfomance-link" %>
      <div>
        <span>Спектакль: <%= review.perfomance.title %> </span> |
        <span>Оценка: <%= review.rating %> / 10 </span>
      </div>
    </div>
    <hr>
  <% end %>
</div>

<div class="but">
  <ul>
    <%= link_to "Назад", root_path, class: "button" %>
    <%= link_to "Добавить новый отзыв", new_review_path, class: "button" %>
  </ul>
</div>

app/views/reviews/new.html.erb
<h1>Добавить новый отзыв</h1>
<%= render 'review_form' %>

app/views/reviews/show.html.erb
<h1>Отзыв на спектакль "<%= @review.perfomance.title %>"</h1>
<hr>
<div>
  <p><strong>Пользователь:</strong> <%= @review.user_name %></p>
  <p><strong>Спектакль:</strong> <%= @review.perfomance.title %></p>
  <p><strong>Оценка:</strong> <%= @review.rating %> / 10</p>
  <p><strong>Отзыв:</strong> <%= @review.review_text %></p>
  <p><strong>Дата просмотра спектакля:</strong> <%= @review.review_date.strftime('%d.%m.%Y') %></p>
</div>

<div class="actions">
  <%= link_to 'Назад', reviews_path, class: 'button' %>
  <%= link_to 'Редактировать', edit_review_path(@review), class: 'button' %>
  <%= form_with model: @review, method: :delete do |form| %>
    <button type="submit" onclick="return confirm('Удалить этот отзыв?')" class="button">
      Удалить
    </button>
   <% end %>
</div>

<hr>

<h2>Другие отзывы пользователя</h2>

<div>
  <% if @other_reviews.any? %>
    <% @other_reviews.each do |other_review| %>
      <div>
        <p><strong><%= link_to 'Отзыв', review_path(other_review) %></strong> на спектакль: <%= other_review.perfomance.title %></p>
        <p><strong>Дата отзыва:</strong> <%= other_review.review_date.strftime('%d.%m.%Y') %> </p>
        <hr>
      </div>
    <% end %>
  <% else %>
    <p>У этого пользователя нет других отзывов.</p>
  <% end %>
</div>